import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "../styles/scss/style.scss"
import { useRef } from "react";
import { LayoutTransition } from "./components/LayoutTransition";
import { Roboto_Mono, Roboto } from "next/font/google"
import QueryProvider from "./components/CustomQueryProvider";
import Navbar from "./components/Navbar/navbar";
import { faCalendar } from "@fortawesome/free-regular-svg-icons";
import { CookieConsent } from "./components/cookies/Cookiebanner";


const roboto = Roboto({
  weight: ["500", "700", "900"],
  subsets: ["latin"]
})

const roboto_mono = Roboto_Mono({
  weight: ["400", "500", "600"],
  subsets: ["latin"]
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <html lang="en">
      <body
        className={`${roboto.style} ${roboto_mono.style} antialiased`}
      >
        <QueryProvider>
          <LayoutTransition
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="content-grid"
          >
            {children}
          </LayoutTransition>
        </QueryProvider>
        <CookieConsent />
      </body>
    </html>
  );
}
