/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/haus.glb --types -M 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { motion } from 'framer-motion-3d'

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh
  }
  materials: {}
  animations: any[]
}

export function Haus(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/haus.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} position={[0.071, 6.469, -12.369]} scale={[6.324, 5.511, 10.104]} >
        <motion.meshStandardMaterial color="white" />
      </mesh>
    </group>
  )
}

useGLTF.preload('/haus.glb')
