/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/house.glb --types -M 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Mesh344: THREE.Mesh
    Mesh344_1: THREE.Mesh
    Mesh344_2: THREE.Mesh
    Mesh344_3: THREE.Mesh
    Mesh344_4: THREE.Mesh
    Mesh451: THREE.Mesh
    Mesh451_1: THREE.Mesh
    Mesh435: THREE.Mesh
    Mesh435_1: THREE.Mesh
    Mesh375: THREE.Mesh
    Mesh375_1: THREE.Mesh
    Mesh343: THREE.Mesh
    Mesh343_1: THREE.Mesh
    Mesh358: THREE.Mesh
    Mesh358_1: THREE.Mesh
    Mesh366: THREE.Mesh
    Mesh366_1: THREE.Mesh
    Mesh363: THREE.Mesh
    Mesh363_1: THREE.Mesh
    Mesh129: THREE.Mesh
    Mesh130: THREE.Mesh
    Mesh362: THREE.Mesh
    Mesh362_1: THREE.Mesh
    Mesh362_2: THREE.Mesh
    Mesh349: THREE.Mesh
    Mesh349_1: THREE.Mesh
    Mesh349_2: THREE.Mesh
    Mesh357: THREE.Mesh
    Mesh357_1: THREE.Mesh
    Mesh357_2: THREE.Mesh
    Mesh357_3: THREE.Mesh
    Mesh357_4: THREE.Mesh
    Mesh350: THREE.Mesh
    Mesh350_1: THREE.Mesh
    Mesh355: THREE.Mesh
    Mesh355_1: THREE.Mesh
    Mesh356: THREE.Mesh
    Mesh356_1: THREE.Mesh
    Mesh351: THREE.Mesh
    Mesh351_1: THREE.Mesh
    Mesh352: THREE.Mesh
    Mesh352_1: THREE.Mesh
    Mesh353: THREE.Mesh
    Mesh353_1: THREE.Mesh
    Mesh354: THREE.Mesh
    Mesh354_1: THREE.Mesh
    Mesh467: THREE.Mesh
    Mesh467_1: THREE.Mesh
    Mesh466: THREE.Mesh
    Mesh466_1: THREE.Mesh
    Mesh468: THREE.Mesh
    Mesh468_1: THREE.Mesh
    Mesh469: THREE.Mesh
    Mesh469_1: THREE.Mesh
    Mesh347: THREE.Mesh
    Mesh347_1: THREE.Mesh
    Mesh348: THREE.Mesh
    Mesh348_1: THREE.Mesh
    Mesh452: THREE.Mesh
    Mesh452_1: THREE.Mesh
    Mesh463: THREE.Mesh
    Mesh463_1: THREE.Mesh
    Mesh470: THREE.Mesh
    Mesh470_1: THREE.Mesh
    Mesh471: THREE.Mesh
    Mesh471_1: THREE.Mesh
    Mesh453: THREE.Mesh
    Mesh453_1: THREE.Mesh
    Mesh454: THREE.Mesh
    Mesh454_1: THREE.Mesh
    Mesh455: THREE.Mesh
    Mesh455_1: THREE.Mesh
    Mesh456: THREE.Mesh
    Mesh456_1: THREE.Mesh
    Mesh457: THREE.Mesh
    Mesh457_1: THREE.Mesh
    Mesh460: THREE.Mesh
    Mesh460_1: THREE.Mesh
    Mesh461: THREE.Mesh
    Mesh461_1: THREE.Mesh
    Mesh462: THREE.Mesh
    Mesh462_1: THREE.Mesh
    Mesh458: THREE.Mesh
    Mesh458_1: THREE.Mesh
    Mesh459: THREE.Mesh
    Mesh459_1: THREE.Mesh
    Mesh359: THREE.Mesh
    Mesh359_1: THREE.Mesh
    Mesh360: THREE.Mesh
    Mesh360_1: THREE.Mesh
    Mesh376: THREE.Mesh
    Mesh376_1: THREE.Mesh
    Mesh376_2: THREE.Mesh
    Mesh374: THREE.Mesh
    Mesh374_1: THREE.Mesh
    Mesh377: THREE.Mesh
    Mesh377_1: THREE.Mesh
    Mesh377_2: THREE.Mesh
    Mesh377_3: THREE.Mesh
    Mesh378: THREE.Mesh
    Mesh378_1: THREE.Mesh
    Mesh378_2: THREE.Mesh
    Mesh386: THREE.Mesh
    Mesh386_1: THREE.Mesh
    Mesh387: THREE.Mesh
    Mesh387_1: THREE.Mesh
    Mesh389: THREE.Mesh
    Mesh389_1: THREE.Mesh
    Mesh395: THREE.Mesh
    Mesh395_1: THREE.Mesh
    Mesh398: THREE.Mesh
    Mesh398_1: THREE.Mesh
    Mesh388: THREE.Mesh
    Mesh388_1: THREE.Mesh
    Mesh392: THREE.Mesh
    Mesh392_1: THREE.Mesh
    Mesh393: THREE.Mesh
    Mesh393_1: THREE.Mesh
    Mesh394: THREE.Mesh
    Mesh394_1: THREE.Mesh
    Mesh396: THREE.Mesh
    Mesh396_1: THREE.Mesh
    Mesh397: THREE.Mesh
    Mesh397_1: THREE.Mesh
    Mesh155: THREE.Mesh
    Mesh391: THREE.Mesh
    Mesh391_1: THREE.Mesh
    Mesh380: THREE.Mesh
    Mesh380_1: THREE.Mesh
    Mesh381: THREE.Mesh
    Mesh381_1: THREE.Mesh
    Mesh382: THREE.Mesh
    Mesh382_1: THREE.Mesh
    Mesh383: THREE.Mesh
    Mesh383_1: THREE.Mesh
    Mesh384: THREE.Mesh
    Mesh384_1: THREE.Mesh
    Mesh385: THREE.Mesh
    Mesh385_1: THREE.Mesh
    Mesh399: THREE.Mesh
    Mesh399_1: THREE.Mesh
    Mesh422: THREE.Mesh
    Mesh422_1: THREE.Mesh
    Mesh424: THREE.Mesh
    Mesh424_1: THREE.Mesh
    Mesh430: THREE.Mesh
    Mesh430_1: THREE.Mesh
    Mesh433: THREE.Mesh
    Mesh433_1: THREE.Mesh
    Mesh421: THREE.Mesh
    Mesh421_1: THREE.Mesh
    Mesh423: THREE.Mesh
    Mesh423_1: THREE.Mesh
    Mesh427: THREE.Mesh
    Mesh427_1: THREE.Mesh
    Mesh428: THREE.Mesh
    Mesh428_1: THREE.Mesh
    Mesh429: THREE.Mesh
    Mesh429_1: THREE.Mesh
    Mesh431: THREE.Mesh
    Mesh431_1: THREE.Mesh
    Mesh432: THREE.Mesh
    Mesh432_1: THREE.Mesh
    Mesh190: THREE.Mesh
    Mesh426: THREE.Mesh
    Mesh426_1: THREE.Mesh
    Mesh418: THREE.Mesh
    Mesh418_1: THREE.Mesh
    Mesh419: THREE.Mesh
    Mesh419_1: THREE.Mesh
    Mesh420: THREE.Mesh
    Mesh420_1: THREE.Mesh
    Mesh415: THREE.Mesh
    Mesh415_1: THREE.Mesh
    Mesh416: THREE.Mesh
    Mesh416_1: THREE.Mesh
    Mesh417: THREE.Mesh
    Mesh417_1: THREE.Mesh
    Mesh434: THREE.Mesh
    Mesh434_1: THREE.Mesh
    Mesh436: THREE.Mesh
    Mesh436_1: THREE.Mesh
    Mesh436_2: THREE.Mesh
    Mesh400: THREE.Mesh
    Mesh400_1: THREE.Mesh
    Mesh404: THREE.Mesh
    Mesh404_1: THREE.Mesh
    Mesh407: THREE.Mesh
    Mesh407_1: THREE.Mesh
    Mesh408: THREE.Mesh
    Mesh408_1: THREE.Mesh
    Mesh402: THREE.Mesh
    Mesh402_1: THREE.Mesh
    Mesh403: THREE.Mesh
    Mesh403_1: THREE.Mesh
    Mesh405: THREE.Mesh
    Mesh405_1: THREE.Mesh
    Mesh166: THREE.Mesh
    Mesh410: THREE.Mesh
    Mesh410_1: THREE.Mesh
    Mesh411: THREE.Mesh
    Mesh411_1: THREE.Mesh
    Mesh412: THREE.Mesh
    Mesh412_1: THREE.Mesh
    Mesh406: THREE.Mesh
    Mesh406_1: THREE.Mesh
    Mesh409: THREE.Mesh
    Mesh409_1: THREE.Mesh
    Mesh379: THREE.Mesh
    Mesh379_1: THREE.Mesh
    Mesh379_2: THREE.Mesh
    Mesh464: THREE.Mesh
    Mesh464_1: THREE.Mesh
    Mesh465: THREE.Mesh
    Mesh465_1: THREE.Mesh
    Mesh443: THREE.Mesh
    Mesh443_1: THREE.Mesh
    Mesh444: THREE.Mesh
    Mesh444_1: THREE.Mesh
    Mesh445: THREE.Mesh
    Mesh445_1: THREE.Mesh
    Mesh448: THREE.Mesh
    Mesh448_1: THREE.Mesh
    Mesh446: THREE.Mesh
    Mesh446_1: THREE.Mesh
    Mesh447: THREE.Mesh
    Mesh447_1: THREE.Mesh
    Mesh449: THREE.Mesh
    Mesh449_1: THREE.Mesh
    Mesh437: THREE.Mesh
    Mesh437_1: THREE.Mesh
    Mesh438: THREE.Mesh
    Mesh438_1: THREE.Mesh
    Mesh439: THREE.Mesh
    Mesh439_1: THREE.Mesh
    Mesh440: THREE.Mesh
    Mesh440_1: THREE.Mesh
    Mesh441: THREE.Mesh
    Mesh441_1: THREE.Mesh
    Mesh442: THREE.Mesh
    Mesh442_1: THREE.Mesh
    Mesh215: THREE.Mesh
    Mesh178: THREE.Mesh
    Mesh414: THREE.Mesh
    Mesh414_1: THREE.Mesh
    Mesh236_1: THREE.Mesh
    Mesh236_2: THREE.Mesh
    Mesh245: THREE.Mesh
    Mesh245_1: THREE.Mesh
    Mesh246: THREE.Mesh
    Mesh246_1: THREE.Mesh
    Mesh247: THREE.Mesh
    Mesh247_1: THREE.Mesh
    Mesh248: THREE.Mesh
    Mesh248_1: THREE.Mesh
    Mesh249: THREE.Mesh
    Mesh249_1: THREE.Mesh
    Mesh250: THREE.Mesh
    Mesh250_1: THREE.Mesh
    Mesh251: THREE.Mesh
    Mesh251_1: THREE.Mesh
    Mesh252: THREE.Mesh
    Mesh252_1: THREE.Mesh
    Mesh253: THREE.Mesh
    Mesh253_1: THREE.Mesh
    Mesh254: THREE.Mesh
    Mesh254_1: THREE.Mesh
    Mesh237: THREE.Mesh
    Mesh237_1: THREE.Mesh
    Mesh255: THREE.Mesh
    Mesh255_1: THREE.Mesh
    Mesh256: THREE.Mesh
    Mesh256_1: THREE.Mesh
    Mesh238: THREE.Mesh
    Mesh238_1: THREE.Mesh
    Mesh239: THREE.Mesh
    Mesh239_1: THREE.Mesh
    Mesh240: THREE.Mesh
    Mesh240_1: THREE.Mesh
    Mesh241: THREE.Mesh
    Mesh241_1: THREE.Mesh
    Mesh242: THREE.Mesh
    Mesh242_1: THREE.Mesh
    Mesh243: THREE.Mesh
    Mesh243_1: THREE.Mesh
    Mesh244: THREE.Mesh
    Mesh244_1: THREE.Mesh
    Mesh312: THREE.Mesh
    Mesh312_1: THREE.Mesh
    Mesh311: THREE.Mesh
    Mesh311_1: THREE.Mesh
    Mesh313: THREE.Mesh
    Mesh313_1: THREE.Mesh
    Mesh314: THREE.Mesh
    Mesh314_1: THREE.Mesh
    Mesh315: THREE.Mesh
    Mesh315_1: THREE.Mesh
    Mesh272: THREE.Mesh
    Mesh272_1: THREE.Mesh
    Mesh273: THREE.Mesh
    Mesh273_1: THREE.Mesh
    Mesh274: THREE.Mesh
    Mesh274_1: THREE.Mesh
    Mesh284: THREE.Mesh
    Mesh284_1: THREE.Mesh
    Mesh278: THREE.Mesh
    Mesh278_1: THREE.Mesh
    Mesh275: THREE.Mesh
    Mesh275_1: THREE.Mesh
    Mesh276: THREE.Mesh
    Mesh276_1: THREE.Mesh
    Mesh277: THREE.Mesh
    Mesh277_1: THREE.Mesh
    Mesh282: THREE.Mesh
    Mesh282_1: THREE.Mesh
    Mesh279: THREE.Mesh
    Mesh279_1: THREE.Mesh
    Mesh280: THREE.Mesh
    Mesh280_1: THREE.Mesh
    Mesh281: THREE.Mesh
    Mesh281_1: THREE.Mesh
    Mesh283: THREE.Mesh
    Mesh283_1: THREE.Mesh
    Mesh285: THREE.Mesh
    Mesh285_1: THREE.Mesh
    Mesh286: THREE.Mesh
    Mesh286_1: THREE.Mesh
    Mesh287: THREE.Mesh
    Mesh287_1: THREE.Mesh
    Mesh297: THREE.Mesh
    Mesh297_1: THREE.Mesh
    Mesh291: THREE.Mesh
    Mesh291_1: THREE.Mesh
    Mesh288: THREE.Mesh
    Mesh288_1: THREE.Mesh
    Mesh290: THREE.Mesh
    Mesh290_1: THREE.Mesh
    Mesh289: THREE.Mesh
    Mesh289_1: THREE.Mesh
    Mesh295: THREE.Mesh
    Mesh295_1: THREE.Mesh
    Mesh292: THREE.Mesh
    Mesh292_1: THREE.Mesh
    Mesh293: THREE.Mesh
    Mesh293_1: THREE.Mesh
    Mesh294: THREE.Mesh
    Mesh294_1: THREE.Mesh
    Mesh296: THREE.Mesh
    Mesh296_1: THREE.Mesh
    Mesh298: THREE.Mesh
    Mesh298_1: THREE.Mesh
    Mesh299: THREE.Mesh
    Mesh299_1: THREE.Mesh
    Mesh300: THREE.Mesh
    Mesh300_1: THREE.Mesh
    Mesh310: THREE.Mesh
    Mesh310_1: THREE.Mesh
    Mesh304: THREE.Mesh
    Mesh304_1: THREE.Mesh
    Mesh301: THREE.Mesh
    Mesh301_1: THREE.Mesh
    Mesh302: THREE.Mesh
    Mesh302_1: THREE.Mesh
    Mesh303: THREE.Mesh
    Mesh303_1: THREE.Mesh
    Mesh308: THREE.Mesh
    Mesh308_1: THREE.Mesh
    Mesh305: THREE.Mesh
    Mesh305_1: THREE.Mesh
    Mesh306: THREE.Mesh
    Mesh306_1: THREE.Mesh
    Mesh307: THREE.Mesh
    Mesh307_1: THREE.Mesh
    Mesh309: THREE.Mesh
    Mesh309_1: THREE.Mesh
    Mesh316: THREE.Mesh
    Mesh316_1: THREE.Mesh
    Mesh317: THREE.Mesh
    Mesh317_1: THREE.Mesh
    Mesh318: THREE.Mesh
    Mesh318_1: THREE.Mesh
    Mesh328: THREE.Mesh
    Mesh328_1: THREE.Mesh
    Mesh322: THREE.Mesh
    Mesh322_1: THREE.Mesh
    Mesh319: THREE.Mesh
    Mesh319_1: THREE.Mesh
    Mesh320: THREE.Mesh
    Mesh320_1: THREE.Mesh
    Mesh321: THREE.Mesh
    Mesh321_1: THREE.Mesh
    Mesh326: THREE.Mesh
    Mesh326_1: THREE.Mesh
    Mesh323: THREE.Mesh
    Mesh323_1: THREE.Mesh
    Mesh324: THREE.Mesh
    Mesh324_1: THREE.Mesh
    Mesh325: THREE.Mesh
    Mesh325_1: THREE.Mesh
    Mesh327: THREE.Mesh
    Mesh327_1: THREE.Mesh
    Mesh98: THREE.Mesh
    Mesh330: THREE.Mesh
    Mesh330_1: THREE.Mesh
    Mesh331: THREE.Mesh
    Mesh331_1: THREE.Mesh
    Mesh332: THREE.Mesh
    Mesh332_1: THREE.Mesh
    Mesh334: THREE.Mesh
    Mesh334_1: THREE.Mesh
    Mesh335: THREE.Mesh
    Mesh335_1: THREE.Mesh
    Mesh336: THREE.Mesh
    Mesh336_1: THREE.Mesh
    Mesh340: THREE.Mesh
    Mesh340_1: THREE.Mesh
    Mesh342: THREE.Mesh
    Mesh342_1: THREE.Mesh
    Mesh103: THREE.Mesh
    Mesh104: THREE.Mesh
    Mesh106: THREE.Mesh
    Mesh337: THREE.Mesh
    Mesh337_1: THREE.Mesh
    Mesh257: THREE.Mesh
    Mesh257_1: THREE.Mesh
    Mesh258: THREE.Mesh
    Mesh258_1: THREE.Mesh
    Mesh258_2: THREE.Mesh
    Mesh265: THREE.Mesh
    Mesh265_1: THREE.Mesh
    Mesh266: THREE.Mesh
    Mesh266_1: THREE.Mesh
    Mesh266_2: THREE.Mesh
    Mesh264: THREE.Mesh
    Mesh264_1: THREE.Mesh
    Mesh269: THREE.Mesh
    Mesh269_1: THREE.Mesh
    Mesh270: THREE.Mesh
    Mesh270_1: THREE.Mesh
    Mesh268: THREE.Mesh
    Mesh268_1: THREE.Mesh
    Mesh271: THREE.Mesh
    Mesh271_1: THREE.Mesh
    Mesh271_2: THREE.Mesh
    Mesh271_3: THREE.Mesh
    Mesh267: THREE.Mesh
    Mesh267_1: THREE.Mesh
    Mesh267_2: THREE.Mesh
    Mesh259: THREE.Mesh
    Mesh259_1: THREE.Mesh
    Mesh260: THREE.Mesh
    Mesh260_1: THREE.Mesh
    Mesh261: THREE.Mesh
    Mesh261_1: THREE.Mesh
    Mesh262: THREE.Mesh
    Mesh262_1: THREE.Mesh
    Mesh263: THREE.Mesh
    Mesh263_1: THREE.Mesh
    Mesh361: THREE.Mesh
    Mesh361_1: THREE.Mesh
    Mesh361_2: THREE.Mesh
    Mesh361_3: THREE.Mesh
    Mesh361_4: THREE.Mesh
    Mesh329: THREE.Mesh
    Mesh329_1: THREE.Mesh
    Mesh329_2: THREE.Mesh
    Mesh329_3: THREE.Mesh
    Mesh345: THREE.Mesh
    Mesh345_1: THREE.Mesh
    Mesh346: THREE.Mesh
    Mesh346_1: THREE.Mesh
    Mesh132: THREE.Mesh
    Mesh368: THREE.Mesh
    Mesh368_1: THREE.Mesh
    Mesh368_2: THREE.Mesh
    Mesh369: THREE.Mesh
    Mesh369_1: THREE.Mesh
    Mesh370: THREE.Mesh
    Mesh370_1: THREE.Mesh
    Mesh370_2: THREE.Mesh
    Mesh371: THREE.Mesh
    Mesh371_1: THREE.Mesh
    Mesh371_2: THREE.Mesh
    Mesh371_3: THREE.Mesh
    Mesh372: THREE.Mesh
    Mesh372_1: THREE.Mesh
    Mesh138: THREE.Mesh
  }
  materials: {
    ['Color_000_ceramic.001']: THREE.MeshStandardMaterial
    ['_auto_4.001']: THREE.MeshStandardMaterial
    ['Color_M00.001']: THREE.MeshStandardMaterial
    ['Metal_Silver.001']: THREE.MeshStandardMaterial
    ['Metal_Aluminum_Anodized.001']: THREE.MeshStandardMaterial
    ['FrontColor.001']: THREE.MeshStandardMaterial
    ['BackColor.001']: THREE.MeshStandardMaterial
    ['_.001']: THREE.MeshStandardMaterial
    ['Polished_Concrete_New.001']: THREE.MeshStandardMaterial
    ['Square_Glass_Tile_01.001']: THREE.MeshStandardMaterial
    ['Wood_Veneer_02.001']: THREE.MeshStandardMaterial
    ['Ceramic_White.001']: THREE.MeshStandardMaterial
    ['Color_M04.001']: THREE.MeshStandardMaterial
    ['Chrome_Polished.001']: THREE.MeshStandardMaterial
    ['Metal_Corrugated_Shiny.001']: THREE.MeshStandardMaterial
    ['Translucent_Glass_Blue.001']: THREE.MeshStandardMaterial
    ['Blinds_Roman_Hobbled_Blue.001']: THREE.MeshStandardMaterial
    ['Formica_Blue.001']: THREE.MeshStandardMaterial
    ['Carpet_Berber_Pattern_Gray.001']: THREE.MeshStandardMaterial
    ['Concrete_Aggregate_Smoke.001']: THREE.MeshStandardMaterial
    ['_3.001']: THREE.MeshStandardMaterial
    ['_2.001']: THREE.MeshStandardMaterial
    ['Aluminum.001']: THREE.MeshStandardMaterial
    ['Color_M09.001']: THREE.MeshStandardMaterial
    ['Black2.001']: THREE.MeshStandardMaterial
    ['chrome2.001']: THREE.MeshStandardMaterial
    ['M_0136_Charcoal.001']: THREE.MeshStandardMaterial
    ['_1.001']: THREE.MeshStandardMaterial
    ['Color_M01.001']: THREE.MeshStandardMaterial
    ['Paint_01.001']: THREE.MeshStandardMaterial
    ['Paint_05.001']: THREE.MeshStandardMaterial
    ['Mtl_Stainless_Steel.001']: THREE.MeshStandardMaterial
    ['Glass_Blue.001']: THREE.MeshStandardMaterial
    ['Paint_06.001']: THREE.MeshStandardMaterial
    ['Mat3d66_512505_1_584_Map__21_0_1.001']: THREE.MeshStandardMaterial
    ['Mat3d66_512505_2_213_0_2.001']: THREE.MeshStandardMaterial
    ['Color_M05.001']: THREE.MeshStandardMaterial
    ['Subsurf.001']: THREE.MeshStandardMaterial
    ['Color_I08.001']: THREE.MeshStandardMaterial
    ['Subsurf1.001']: THREE.MeshStandardMaterial
    ['Color_A08.001']: THREE.MeshStandardMaterial
    ['___005.001']: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/house.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
        <mesh geometry={nodes.Mesh344.geometry} material={materials['Color_000_ceramic.001']} />
        <mesh geometry={nodes.Mesh344_1.geometry} material={materials['_auto_4.001']} />
        <mesh geometry={nodes.Mesh344_2.geometry} material={materials['Color_M00.001']} />
        <mesh geometry={nodes.Mesh344_3.geometry} material={materials['Metal_Silver.001']} />
        <mesh geometry={nodes.Mesh344_4.geometry} material={materials['Metal_Aluminum_Anodized.001']} />
        <mesh geometry={nodes.Mesh451.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh451_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh435.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh435_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh375.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh375_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh343.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh343_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh358.geometry} material={materials['Polished_Concrete_New.001']} />
        <mesh geometry={nodes.Mesh358_1.geometry} material={materials['Square_Glass_Tile_01.001']} />
        <mesh geometry={nodes.Mesh366.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh366_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh363.geometry} material={materials['Ceramic_White.001']} />
        <mesh geometry={nodes.Mesh363_1.geometry} material={materials['Color_M04.001']} />
        <mesh geometry={nodes.Mesh129.geometry} material={materials['Chrome_Polished.001']} />
        <mesh geometry={nodes.Mesh130.geometry} material={materials['Chrome_Polished.001']} />
        <mesh geometry={nodes.Mesh362.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh362_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh362_2.geometry} material={materials['Metal_Corrugated_Shiny.001']} />
        <mesh geometry={nodes.Mesh349.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh349_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh349_2.geometry} material={materials['Translucent_Glass_Blue.001']} />
        <mesh geometry={nodes.Mesh357.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh357_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh357_2.geometry} material={materials['Blinds_Roman_Hobbled_Blue.001']} />
        <mesh geometry={nodes.Mesh357_3.geometry} material={materials['Formica_Blue.001']} />
        <mesh geometry={nodes.Mesh357_4.geometry} material={materials['Square_Glass_Tile_01.001']} />
        <mesh geometry={nodes.Mesh350.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh350_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh355.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh355_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh356.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh356_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh351.geometry} material={materials['Carpet_Berber_Pattern_Gray.001']} />
        <mesh geometry={nodes.Mesh351_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh352.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh352_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh353.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh353_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh354.geometry} material={materials['Carpet_Berber_Pattern_Gray.001']} />
        <mesh geometry={nodes.Mesh354_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh467.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh467_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh466.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh466_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh468.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh468_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh469.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh469_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh347.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh347_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh348.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh348_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh452.geometry} material={materials['Concrete_Aggregate_Smoke.001']} />
        <mesh geometry={nodes.Mesh452_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh463.geometry} material={materials['Concrete_Aggregate_Smoke.001']} />
        <mesh geometry={nodes.Mesh463_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh470.geometry} material={materials['Concrete_Aggregate_Smoke.001']} />
        <mesh geometry={nodes.Mesh470_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh471.geometry} material={materials['Concrete_Aggregate_Smoke.001']} />
        <mesh geometry={nodes.Mesh471_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh453.geometry} material={materials['Concrete_Aggregate_Smoke.001']} />
        <mesh geometry={nodes.Mesh453_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh454.geometry} material={materials['Concrete_Aggregate_Smoke.001']} />
        <mesh geometry={nodes.Mesh454_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh455.geometry} material={materials['Concrete_Aggregate_Smoke.001']} />
        <mesh geometry={nodes.Mesh455_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh456.geometry} material={materials['Concrete_Aggregate_Smoke.001']} />
        <mesh geometry={nodes.Mesh456_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh457.geometry} material={materials['Concrete_Aggregate_Smoke.001']} />
        <mesh geometry={nodes.Mesh457_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh460.geometry} material={materials['Concrete_Aggregate_Smoke.001']} />
        <mesh geometry={nodes.Mesh460_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh461.geometry} material={materials['Concrete_Aggregate_Smoke.001']} />
        <mesh geometry={nodes.Mesh461_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh462.geometry} material={materials['Concrete_Aggregate_Smoke.001']} />
        <mesh geometry={nodes.Mesh462_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh458.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh458_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh459.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh459_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh359.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh359_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh360.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh360_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh376.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh376_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh376_2.geometry} material={materials['Blinds_Roman_Hobbled_Blue.001']} />
        <mesh geometry={nodes.Mesh374.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh374_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh377.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh377_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh377_2.geometry} material={materials['Blinds_Roman_Hobbled_Blue.001']} />
        <mesh geometry={nodes.Mesh377_3.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh378.geometry} material={materials['Blinds_Roman_Hobbled_Blue.001']} />
        <mesh geometry={nodes.Mesh378_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh378_2.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh386.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh386_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh387.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh387_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh389.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh389_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh395.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh395_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh398.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh398_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh388.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh388_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh392.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh392_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh393.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh393_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh394.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh394_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh396.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh396_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh397.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh397_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh155.geometry} material={materials['Translucent_Glass_Blue.001']} />
        <mesh geometry={nodes.Mesh391.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh391_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh380.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh380_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh381.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh381_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh382.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh382_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh383.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh383_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh384.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh384_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh385.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh385_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh399.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh399_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh422.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh422_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh424.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh424_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh430.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh430_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh433.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh433_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh421.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh421_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh423.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh423_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh427.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh427_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh428.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh428_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh429.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh429_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh431.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh431_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh432.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh432_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh190.geometry} material={materials['Translucent_Glass_Blue.001']} />
        <mesh geometry={nodes.Mesh426.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh426_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh418.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh418_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh419.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh419_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh420.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh420_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh415.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh415_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh416.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh416_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh417.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh417_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh434.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh434_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh436.geometry} material={materials['Blinds_Roman_Hobbled_Blue.001']} />
        <mesh geometry={nodes.Mesh436_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh436_2.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh400.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh400_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh404.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh404_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh407.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh407_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh408.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh408_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh402.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh402_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh403.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh403_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh405.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh405_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh166.geometry} material={materials['Translucent_Glass_Blue.001']} />
        <mesh geometry={nodes.Mesh410.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh410_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh411.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh411_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh412.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh412_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh406.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh406_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh409.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh409_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh379.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh379_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh379_2.geometry} material={materials['Blinds_Roman_Hobbled_Blue.001']} />
        <mesh geometry={nodes.Mesh464.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh464_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh465.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh465_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh443.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh443_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh444.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh444_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh445.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh445_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh448.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh448_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh446.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh446_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh447.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh447_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh449.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh449_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh437.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh437_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh438.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh438_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh439.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh439_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh440.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh440_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh441.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh441_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh442.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh442_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh215.geometry} material={materials['Translucent_Glass_Blue.001']} />
        <mesh geometry={nodes.Mesh178.geometry} material={materials['_3.001']} />
        <mesh geometry={nodes.Mesh414.geometry} material={materials['_2.001']} />
        <mesh geometry={nodes.Mesh414_1.geometry} material={materials['_3.001']} />
        <mesh geometry={nodes.Mesh236_1.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh236_2.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh245.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh245_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh246.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh246_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh247.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh247_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh248.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh248_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh249.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh249_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh250.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh250_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh251.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh251_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh252.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh252_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh253.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh253_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh254.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh254_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh237.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh237_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh255.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh255_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh256.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh256_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh238.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh238_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh239.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh239_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh240.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh240_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh241.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh241_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh242.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh242_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh243.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh243_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh244.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh244_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh312.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh312_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh311.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh311_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh313.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh313_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh314.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh314_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh315.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh315_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh272.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh272_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh273.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh273_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh274.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh274_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh284.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh284_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh278.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh278_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh275.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh275_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh276.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh276_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh277.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh277_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh282.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh282_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh279.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh279_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh280.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh280_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh281.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh281_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh283.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh283_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh285.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh285_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh286.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh286_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh287.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh287_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh297.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh297_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh291.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh291_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh288.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh288_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh290.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh290_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh289.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh289_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh295.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh295_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh292.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh292_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh293.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh293_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh294.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh294_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh296.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh296_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh298.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh298_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh299.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh299_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh300.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh300_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh310.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh310_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh304.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh304_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh301.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh301_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh302.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh302_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh303.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh303_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh308.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh308_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh305.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh305_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh306.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh306_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh307.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh307_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh309.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh309_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh316.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh316_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh317.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh317_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh318.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh318_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh328.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh328_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh322.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh322_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh319.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh319_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh320.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh320_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh321.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh321_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh326.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh326_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh323.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh323_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh324.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh324_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh325.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh325_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh327.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh327_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh98.geometry} material={materials['Translucent_Glass_Blue.001']} />
        <mesh geometry={nodes.Mesh330.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh330_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh331.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh331_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh332.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh332_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh334.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh334_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh335.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh335_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh336.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh336_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh340.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh340_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh342.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh342_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh103.geometry} material={materials['Translucent_Glass_Blue.001']} />
        <mesh geometry={nodes.Mesh104.geometry} material={materials['Translucent_Glass_Blue.001']} />
        <mesh geometry={nodes.Mesh106.geometry} material={materials['Translucent_Glass_Blue.001']} />
        <mesh geometry={nodes.Mesh337.geometry} material={materials['_.001']} />
        <mesh geometry={nodes.Mesh337_1.geometry} material={materials['Translucent_Glass_Blue.001']} />
        <mesh geometry={nodes.Mesh257.geometry} material={materials['Metal_Silver.001']} />
        <mesh geometry={nodes.Mesh257_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh258.geometry} material={materials['Aluminum.001']} />
        <mesh geometry={nodes.Mesh258_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh258_2.geometry} material={materials['Color_M09.001']} />
        <mesh geometry={nodes.Mesh265.geometry} material={materials['Metal_Silver.001']} />
        <mesh geometry={nodes.Mesh265_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh266.geometry} material={materials['Aluminum.001']} />
        <mesh geometry={nodes.Mesh266_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh266_2.geometry} material={materials['Color_M09.001']} />
        <mesh geometry={nodes.Mesh264.geometry} material={materials['Wood_Veneer_02.001']} />
        <mesh geometry={nodes.Mesh264_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh269.geometry} material={materials['Black2.001']} />
        <mesh geometry={nodes.Mesh269_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh270.geometry} material={materials['Black2.001']} />
        <mesh geometry={nodes.Mesh270_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh268.geometry} material={materials['Black2.001']} />
        <mesh geometry={nodes.Mesh268_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh271.geometry} material={materials['Black2.001']} />
        <mesh geometry={nodes.Mesh271_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh271_2.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh271_3.geometry} material={materials['chrome2.001']} />
        <mesh geometry={nodes.Mesh267.geometry} material={materials['M_0136_Charcoal.001']} />
        <mesh geometry={nodes.Mesh267_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh267_2.geometry} material={materials['_1.001']} />
        <mesh geometry={nodes.Mesh259.geometry} material={materials['Color_M01.001']} />
        <mesh geometry={nodes.Mesh259_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh260.geometry} material={materials['Color_M01.001']} />
        <mesh geometry={nodes.Mesh260_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh261.geometry} material={materials['Color_M01.001']} />
        <mesh geometry={nodes.Mesh261_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh262.geometry} material={materials['Color_M01.001']} />
        <mesh geometry={nodes.Mesh262_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh263.geometry} material={materials['Color_M01.001']} />
        <mesh geometry={nodes.Mesh263_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh361.geometry} material={materials['Paint_01.001']} />
        <mesh geometry={nodes.Mesh361_1.geometry} material={materials['Paint_05.001']} />
        <mesh geometry={nodes.Mesh361_2.geometry} material={materials['Mtl_Stainless_Steel.001']} />
        <mesh geometry={nodes.Mesh361_3.geometry} material={materials['Glass_Blue.001']} />
        <mesh geometry={nodes.Mesh361_4.geometry} material={materials['Paint_06.001']} />
        <mesh geometry={nodes.Mesh329.geometry} material={materials['Mat3d66_512505_1_584_Map__21_0_1.001']} />
        <mesh geometry={nodes.Mesh329_1.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh329_2.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh329_3.geometry} material={materials['Mat3d66_512505_2_213_0_2.001']} />
        <mesh geometry={nodes.Mesh345.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh345_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh346.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh346_1.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh132.geometry} material={materials['Color_M05.001']} />
        <mesh geometry={nodes.Mesh368.geometry} material={materials['Subsurf.001']} />
        <mesh geometry={nodes.Mesh368_1.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh368_2.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh369.geometry} material={materials['Color_M05.001']} />
        <mesh geometry={nodes.Mesh369_1.geometry} material={materials['Subsurf.001']} />
        <mesh geometry={nodes.Mesh370.geometry} material={materials['Subsurf.001']} />
        <mesh geometry={nodes.Mesh370_1.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh370_2.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh371.geometry} material={materials['FrontColor.001']} />
        <mesh geometry={nodes.Mesh371_1.geometry} material={materials['Color_I08.001']} />
        <mesh geometry={nodes.Mesh371_2.geometry} material={materials['BackColor.001']} />
        <mesh geometry={nodes.Mesh371_3.geometry} material={materials['Subsurf1.001']} />
        <mesh geometry={nodes.Mesh372.geometry} material={materials['Subsurf1.001']} />
        <mesh geometry={nodes.Mesh372_1.geometry} material={materials['Color_A08.001']} />
        <mesh geometry={nodes.Mesh138.geometry} material={materials['___005.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/house.glb')
